name: bit_merge_mobile
description: "<desc>"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State Management helper
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2

  # Core Package
  path_provider: any
  path: ^1.8.3
  intl: ^0.18.1

  # UI
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2

  # Data Package
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  mime: ^1.0.4
  http_parser: ^4.0.2

  # Network Package
  dio: ^5.4.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  uuid: ^4.2.2
  hive: ^2.2.3

  # Utils Package
  flutter_local_notifications: ^16.2.0
  permission_handler: any
  retry: ^3.1.2

  # Firebase Package
  firebase_core: any
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/vector/
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: BitMergeLocalization
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/l10n/generated
  use_deferred_loading: true
